# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: CACS
  params:
    description: Centre for Analysis of Complex Systems of Sechenov University
  menu:
    main:
    - name: Tour
      url: tour
      weight: 10
    - name: News
      url: post
      weight: 20
    - name: People
      url: people
      weight: 30
    - name: Events
      url: event
      weight: 40
    - name: Publications
      url: publication
      weight: 50
    - name: Contact
      url: contact
      weight: 60


# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: ru
  contentDir: content/ru
  title: ЦАСС
  params:
    description: Сайт Центра анализа сложных систем Сеченовского университета
  menu:
    main:
    - name: Публикации
      url: publications
      weight: 10

    - name: Методы
      identifier: methods
      weight: 20
    - name: Репозитарий
      parent: methods
      url: repository
      weight: 10

    - name: Образование
      identifier: education
      url: education
      weight: 30
    - name: Мета-анализ
      parent: education
      url: education/meta_analysis
      weight: 10

    - name: О центре
      url: about
      weight: 40
